services:

    dz.slack.identity_bag:
        class: DZunke\SlackBundle\Slack\Client\IdentityBag

    dz.slack.connection:
        class: DZunke\SlackBundle\Slack\Client\Connection

    dz.slack.client:
        class: DZunke\SlackBundle\Slack\Client
        arguments: [@dz.slack.connection]
        calls:
            - [setIdentityBag, [@dz.slack.identity_bag]]

    dz.slack.messaging:
        class: DZunke\SlackBundle\Slack\Messaging
        arguments: [@dz.slack.client]

    dz.slack.channels:
        class: DZunke\SlackBundle\Slack\Channels
        arguments: [@dz.slack.client]
